apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: app-vault-static-secret
  namespace: test
spec:
  vaultAuthRef: app-vault-auth
  type: kv-v2
  mount: secret
  path: app/config
  refreshAfter: 60s
  destination:
    create: true
    name: app-secret-from-vso
  rolloutRestartTargets:
    - kind: Deployment
      name: myapp
